name: trade_to_ohlc
language: python
variables:
  - name: input
    inputType: InputTopic
    defaultValue: trades_topic
    required: false
  - name: output
    inputType: OutputTopic
    defaultValue: ohlc_topic
    required: false
dockerfile: Dockerfile
runEntryPoint: main.py
defaultFile: main.py
