name: ohlc_to_feature_store
language: python
variables:
  - name: input
    inputType: InputTopic
    defaultValue: ohlc_topic
    required: false
  - name: HOPSWORKS_PROJECT_NAME
    inputType: Secret
    defaultValue: HOPSWORKS_PROJECT_NAME_key
    required: false
  - name: HOPSWORKS_API_KEY
    inputType: Secret
    defaultValue: HOPSWORKS_API_KEY_key
    required: false
dockerfile: Dockerfile
runEntryPoint: main.py
defaultFile: main.py
