name: trade_producer
language: python
variables:
  - name: output
    inputType: OutputTopic
    defaultValue: trades_topic
    required: false
dockerfile: Dockerfile
runEntryPoint: main.py
defaultFile: main.py
